2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110931-1var4zkz/logs/debug.log
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110931-1var4zkz/logs/debug-internal.log
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:09:31,733 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: kzg2r42q
2021-09-21 11:09:31,736 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/kzg2r42q
2021-09-21 11:09:31,810 INFO    MainThread:21744 [jupyter.py:save_history():353] not saving jupyter history
2021-09-21 11:09:31,810 INFO    MainThread:21744 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 11:09:31,810 INFO    MainThread:21744 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-21 11:09:31,810 INFO    MainThread:21744 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-21 11:09:31,810 INFO    MainThread:21744 [wandb_run.py:_restore():1547] restore
2021-09-21 11:09:32,464 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:09:32,957 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:09:33,564 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 10981
}

2021-09-21 11:09:33,668 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 14784
}

2021-09-21 11:09:33,771 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 14784
}

2021-09-21 11:09:33,874 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 14784
}

2021-09-21 11:09:33,977 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 14784
}

2021-09-21 11:09:34,079 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 14784
}

2021-09-21 11:09:34,181 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,285 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,387 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,489 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,592 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,695 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:34,797 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:35,279 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}

2021-09-21 11:09:36,136 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14784
  total_bytes: 14784
}
local_info {
}

2021-09-21 11:09:37,552 INFO    MainThread:21744 [wandb_run.py:_show_summary():1853] rendering summary
2021-09-21 11:09:37,554 INFO    MainThread:21744 [wandb_run.py:_show_history():1898] rendering history
2021-09-21 11:09:37,556 INFO    MainThread:21744 [wandb_run.py:_show_files():1947] logging synced files
2021-09-21 11:09:37,563 INFO    MainThread:21744 [wandb_init.py:init():430] starting backend
2021-09-21 11:09:37,563 INFO    MainThread:21744 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-21 11:09:37,566 INFO    MainThread:21744 [backend.py:ensure_launched():135] starting backend process...
2021-09-21 11:09:37,572 INFO    MainThread:21744 [backend.py:ensure_launched():139] started backend process with pid: 23393
2021-09-21 11:09:37,573 INFO    MainThread:21744 [wandb_init.py:init():435] backend started and connected
2021-09-21 11:09:37,587 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-21 11:09:37,587 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-21 11:09:37,587 INFO    MainThread:21744 [wandb_init.py:init():494] updated telemetry
2021-09-21 11:09:37,588 INFO    MainThread:21744 [wandb_init.py:init():517] communicating current version
2021-09-21 11:09:38,506 INFO    MainThread:21744 [wandb_init.py:init():522] got version response 
2021-09-21 11:09:38,506 INFO    MainThread:21744 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-21 11:09:38,953 INFO    MainThread:21744 [wandb_init.py:init():557] starting run threads in backend
2021-09-21 11:09:40,000 INFO    MainThread:21744 [wandb_run.py:_console_start():1605] atexit reg
2021-09-21 11:09:40,000 INFO    MainThread:21744 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-21 11:09:40,001 INFO    MainThread:21744 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-21 11:09:40,003 INFO    MainThread:21744 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-21 11:09:40,003 INFO    MainThread:21744 [wandb_init.py:init():582] run started, returning control to user process
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110940-2kvpsvny/logs/debug.log
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110940-2kvpsvny/logs/debug-internal.log
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f56b5c8b3d0>
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1var4zkz
2021-09-21 11:09:40,961 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/1var4zkz
