2021-09-21 22:14:51,659 INFO    MainThread:11318 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 22:14:51,659 INFO    MainThread:11318 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 22:14:51,660 INFO    MainThread:11318 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_221451-2aq1nwdv/logs/debug.log
2021-09-21 22:14:51,660 INFO    MainThread:11318 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_221451-2aq1nwdv/logs/debug-internal.log
2021-09-21 22:14:51,660 INFO    MainThread:11318 [wandb_init.py:init():381] calling init triggers
2021-09-21 22:14:51,660 INFO    MainThread:11318 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 22:14:51,660 INFO    MainThread:11318 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 38czedtn
2021-09-21 22:14:51,661 INFO    MainThread:11318 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/38czedtn
2021-09-21 22:14:51,688 INFO    MainThread:11318 [jupyter.py:save_history():353] not saving jupyter history
2021-09-21 22:14:51,689 INFO    MainThread:11318 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 22:14:51,689 INFO    MainThread:11318 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-21 22:14:51,689 INFO    MainThread:11318 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-21 22:14:51,689 INFO    MainThread:11318 [wandb_run.py:_restore():1547] restore
2021-09-21 22:14:52,173 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 22:14:52,747 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 22:14:53,618 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:53,720 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:53,823 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:53,927 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:54,031 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:54,134 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4838
}

2021-09-21 22:14:54,237 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,342 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,445 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,547 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,649 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,752 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,856 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:54,961 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:55,176 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}

2021-09-21 22:14:56,083 INFO    MainThread:11318 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4838
  total_bytes: 4838
}
local_info {
}

2021-09-21 22:14:57,351 INFO    MainThread:11318 [wandb_run.py:_show_files():1947] logging synced files
2021-09-21 22:14:57,359 INFO    MainThread:11318 [wandb_init.py:init():430] starting backend
2021-09-21 22:14:57,360 INFO    MainThread:11318 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-21 22:14:57,362 INFO    MainThread:11318 [backend.py:ensure_launched():135] starting backend process...
2021-09-21 22:14:57,366 INFO    MainThread:11318 [backend.py:ensure_launched():139] started backend process with pid: 11424
2021-09-21 22:14:57,367 INFO    MainThread:11318 [wandb_init.py:init():435] backend started and connected
2021-09-21 22:14:57,380 INFO    MainThread:11318 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-21 22:14:57,381 INFO    MainThread:11318 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-21 22:14:57,381 INFO    MainThread:11318 [wandb_init.py:init():494] updated telemetry
2021-09-21 22:14:57,381 INFO    MainThread:11318 [wandb_init.py:init():517] communicating current version
2021-09-21 22:14:58,303 INFO    MainThread:11318 [wandb_init.py:init():522] got version response 
2021-09-21 22:14:58,303 INFO    MainThread:11318 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-21 22:14:58,817 INFO    MainThread:11318 [wandb_init.py:init():557] starting run threads in backend
2021-09-21 22:14:59,835 INFO    MainThread:11318 [wandb_run.py:_console_start():1605] atexit reg
2021-09-21 22:14:59,836 INFO    MainThread:11318 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-21 22:14:59,836 INFO    MainThread:11318 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-21 22:14:59,837 INFO    MainThread:11318 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-21 22:14:59,837 INFO    MainThread:11318 [wandb_init.py:init():582] run started, returning control to user process
