2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111136-1n8uc4gl/logs/debug.log
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111136-1n8uc4gl/logs/debug-internal.log
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:11:36,849 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:11:36,849 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 2kvpsvny
2021-09-21 11:11:36,850 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/Set-Tree-graphtree/2kvpsvny
2021-09-21 11:11:36,850 INFO    MainThread:21744 [jupyter.py:save_history():353] not saving jupyter history
2021-09-21 11:11:36,850 INFO    MainThread:21744 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 11:11:36,850 INFO    MainThread:21744 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-21 11:11:36,850 INFO    MainThread:21744 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-21 11:11:36,851 INFO    MainThread:21744 [wandb_run.py:_restore():1547] restore
2021-09-21 11:11:37,291 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:11:37,745 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:11:38,129 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,232 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,334 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,437 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,539 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,646 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5655
}

2021-09-21 11:11:38,748 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:38,852 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:38,956 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:39,061 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:39,164 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:39,267 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:39,370 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:39,791 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}

2021-09-21 11:11:40,671 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5655
  total_bytes: 5655
}
local_info {
}

2021-09-21 11:11:41,968 INFO    MainThread:21744 [wandb_run.py:_show_files():1947] logging synced files
2021-09-21 11:11:41,975 INFO    MainThread:21744 [wandb_init.py:init():430] starting backend
2021-09-21 11:11:41,975 INFO    MainThread:21744 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-21 11:11:41,980 INFO    MainThread:21744 [backend.py:ensure_launched():135] starting backend process...
2021-09-21 11:11:41,985 INFO    MainThread:21744 [backend.py:ensure_launched():139] started backend process with pid: 23712
2021-09-21 11:11:41,986 INFO    MainThread:21744 [wandb_init.py:init():435] backend started and connected
2021-09-21 11:11:42,002 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-21 11:11:42,002 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-21 11:11:42,002 INFO    MainThread:21744 [wandb_init.py:init():494] updated telemetry
2021-09-21 11:11:42,003 INFO    MainThread:21744 [wandb_init.py:init():517] communicating current version
2021-09-21 11:11:43,036 INFO    MainThread:21744 [wandb_init.py:init():522] got version response 
2021-09-21 11:11:43,036 INFO    MainThread:21744 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-21 11:11:43,599 INFO    MainThread:21744 [wandb_init.py:init():557] starting run threads in backend
2021-09-21 11:11:44,634 INFO    MainThread:21744 [wandb_run.py:_console_start():1605] atexit reg
2021-09-21 11:11:44,635 INFO    MainThread:21744 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-21 11:11:44,635 INFO    MainThread:21744 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-21 11:11:44,636 INFO    MainThread:21744 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-21 11:11:44,636 INFO    MainThread:21744 [wandb_init.py:init():582] run started, returning control to user process
2021-09-21 11:11:45,666 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:11:45,666 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:11:45,666 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:11:45,666 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111145-27l3euuz/logs/debug.log
2021-09-21 11:11:45,667 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111145-27l3euuz/logs/debug-internal.log
2021-09-21 11:11:45,667 INFO    MainThread:21744 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f56b5cc31f0>
2021-09-21 11:11:45,667 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:11:45,667 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:11:45,667 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1n8uc4gl
2021-09-21 11:11:45,669 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/1n8uc4gl
