2021-09-21 19:07:03,113 INFO    MainThread:24652 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 19:07:03,113 INFO    MainThread:24652 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 19:07:03,113 INFO    MainThread:24652 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_190703-3ofmraag/logs/debug.log
2021-09-21 19:07:03,113 INFO    MainThread:24652 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_190703-3ofmraag/logs/debug-internal.log
2021-09-21 19:07:03,114 INFO    MainThread:24652 [wandb_init.py:init():381] calling init triggers
2021-09-21 19:07:03,114 INFO    MainThread:24652 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 19:07:03,114 INFO    MainThread:24652 [wandb_init.py:init():401] re-initializing run, found existing run on stack: g956sdhm
2021-09-21 19:07:03,115 INFO    MainThread:24652 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/g956sdhm
2021-09-21 19:07:03,140 INFO    MainThread:24652 [jupyter.py:save_history():353] not saving jupyter history
2021-09-21 19:07:03,140 INFO    MainThread:24652 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 19:07:03,140 INFO    MainThread:24652 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-21 19:07:03,140 INFO    MainThread:24652 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-21 19:07:03,140 INFO    MainThread:24652 [wandb_run.py:_restore():1547] restore
2021-09-21 19:07:03,815 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 19:07:04,435 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 19:07:04,599 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 1196
}

2021-09-21 19:07:04,702 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5061
}

2021-09-21 19:07:04,805 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5061
}

2021-09-21 19:07:04,909 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5061
}

2021-09-21 19:07:05,013 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5061
}

2021-09-21 19:07:05,116 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 5061
}

2021-09-21 19:07:05,218 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 999
  total_bytes: 5061
}

2021-09-21 19:07:05,321 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:05,425 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:05,529 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:05,631 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:05,734 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:05,836 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:06,053 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}

2021-09-21 19:07:06,944 INFO    MainThread:24652 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5061
  total_bytes: 5061
}
local_info {
}

2021-09-21 19:07:08,214 INFO    MainThread:24652 [wandb_run.py:_show_files():1947] logging synced files
2021-09-21 19:07:08,222 INFO    MainThread:24652 [wandb_init.py:init():430] starting backend
2021-09-21 19:07:08,222 INFO    MainThread:24652 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-21 19:07:08,226 INFO    MainThread:24652 [backend.py:ensure_launched():135] starting backend process...
2021-09-21 19:07:08,232 INFO    MainThread:24652 [backend.py:ensure_launched():139] started backend process with pid: 24762
2021-09-21 19:07:08,233 INFO    MainThread:24652 [wandb_init.py:init():435] backend started and connected
2021-09-21 19:07:08,253 INFO    MainThread:24652 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-21 19:07:08,253 INFO    MainThread:24652 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-21 19:07:08,253 INFO    MainThread:24652 [wandb_init.py:init():494] updated telemetry
2021-09-21 19:07:08,254 INFO    MainThread:24652 [wandb_init.py:init():517] communicating current version
2021-09-21 19:07:09,193 INFO    MainThread:24652 [wandb_init.py:init():522] got version response 
2021-09-21 19:07:09,193 INFO    MainThread:24652 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-21 19:07:09,658 INFO    MainThread:24652 [wandb_init.py:init():557] starting run threads in backend
2021-09-21 19:07:10,770 INFO    MainThread:24652 [wandb_run.py:_console_start():1605] atexit reg
2021-09-21 19:07:10,771 INFO    MainThread:24652 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-21 19:07:10,772 INFO    MainThread:24652 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-21 19:07:10,773 INFO    MainThread:24652 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-21 19:07:10,774 INFO    MainThread:24652 [wandb_init.py:init():582] run started, returning control to user process
